<template>
  <ul role="list" id="searchResults" class="theContent divide-y divide-gray-200 dark:divide-gray-800">
    <li v-for="(d, i) in data" :key="i" class="">
      <a :href="d.url" class="font-bold">
        {{ d.name }}
      </a>
      <a :href="d.url" class=""> ip Address:
        <span class="primaryText">{{ d.ip_address }}</span>
      </a>
      <span class="items-end dark:text-slate-600 text-neutral-600">
        &nbsp; Created on {{ d.date }}
        &nbsp; . &nbsp; Rated:
        <span class="primaryText">{{ d.id }}</span>
      </span>
    </li>
  </ul>
</template>

<script setup>
const data = [
  { "id": 1, "ip_address": "31.138.86.130", "name": "Quo Lux", "url": "http://java.com/rutrum/rutrum/neque/aenean/auctor/gravida.aspx?venenatis=adipiscing&non=elit&sodales=proin&sed=risus&tincidunt=praesent&eu=lectus&felis=vestibulum&fusce=quam&posuere=sapien&felis=varius&sed=ut&lacus=blandit&morbi=non&sem=interdum&mauris=in&laoreet=ante&ut=vestibulum&rhoncus=ante&aliquet=ipsum&pulvinar=primis&sed=in&nisl=faucibus&nunc=orci&rhoncus=luctus&dui=et&vel=ultrices&sem=posuere&sed=cubilia&sagittis=curae&nam=duis&congue=faucibus&risus=accumsan&semper=odio&porta=curabitur", "date": "9/22/2022" },
  { "id": 2, "ip_address": "200.37.82.111", "name": "Bitchip", "url": "http://harvard.edu/duis/mattis/egestas/metus.json?volutpat=consectetuer&sapien=adipiscing&arcu=elit&sed=proin&augue=interdum&aliquam=mauris&erat=non&volutpat=ligula&in=pellentesque&congue=ultrices&etiam=phasellus&justo=id&etiam=sapien&pretium=in&iaculis=sapien&justo=iaculis&in=congue&hac=vivamus&habitasse=metus&platea=arcu&dictumst=adipiscing&etiam=molestie&faucibus=hendrerit&cursus=at&urna=vulputate&ut=vitae&tellus=nisl&nulla=aenean&ut=lectus&erat=pellentesque&id=eget&mauris=nunc&vulputate=donec&elementum=quis&nullam=orci&varius=eget&nulla=orci&facilisi=vehicula&cras=condimentum&non=curabitur&velit=in&nec=libero&nisi=ut&vulputate=massa&nonummy=volutpat&maecenas=convallis&tincidunt=morbi", "date": "10/19/2022" },
  { "id": 3, "ip_address": "192.67.116.81", "name": "Bitchip", "url": "https://buzzfeed.com/ante/ipsum/primis/in.png?pede=nulla&ac=ultrices&diam=aliquet&cras=maecenas&pellentesque=leo&volutpat=odio&dui=condimentum&maecenas=id&tristique=luctus&est=nec&et=molestie&tempus=sed&semper=justo&est=pellentesque&quam=viverra&pharetra=pede&magna=ac&ac=diam&consequat=cras&metus=pellentesque&sapien=volutpat&ut=dui&nunc=maecenas&vestibulum=tristique&ante=est&ipsum=et&primis=tempus", "date": "4/4/2023" },
  { "id": 4, "ip_address": "194.163.121.246", "name": "Tresom", "url": "http://desdev.cn/adipiscing/elit/proin/interdum/mauris.js?lorem=id&vitae=nulla&mattis=ultrices&nibh=aliquet&ligula=maecenas&nec=leo&sem=odio&duis=condimentum&aliquam=id&convallis=luctus&nunc=nec&proin=molestie&at=sed&turpis=justo&a=pellentesque&pede=viverra&posuere=pede&nonummy=ac&integer=diam&non=cras&velit=pellentesque&donec=volutpat&diam=dui&neque=maecenas&vestibulum=tristique&eget=est&vulputate=et&ut=tempus&ultrices=semper&vel=est&augue=quam&vestibulum=pharetra&ante=magna&ipsum=ac&primis=consequat&in=metus&faucibus=sapien&orci=ut&luctus=nunc", "date": "6/23/2022" },
  { "id": 5, "ip_address": "63.13.90.114", "name": "Konklux", "url": "http://amazon.com/nulla/nisl/nunc/nisl.json?etiam=iaculis&faucibus=congue&cursus=vivamus&urna=metus&ut=arcu&tellus=adipiscing&nulla=molestie&ut=hendrerit&erat=at&id=vulputate&mauris=vitae&vulputate=nisl&elementum=aenean&nullam=lectus&varius=pellentesque&nulla=eget&facilisi=nunc&cras=donec&non=quis&velit=orci&nec=eget&nisi=orci&vulputate=vehicula&nonummy=condimentum&maecenas=curabitur&tincidunt=in&lacus=libero&at=ut&velit=massa&vivamus=volutpat&vel=convallis&nulla=morbi&eget=odio&eros=odio&elementum=elementum&pellentesque=eu&quisque=interdum&porta=eu&volutpat=tincidunt&erat=in&quisque=leo&erat=maecenas&eros=pulvinar&viverra=lobortis&eget=est&congue=phasellus&eget=sit&semper=amet&rutrum=erat&nulla=nulla&nunc=tempus&purus=vivamus&phasellus=in&in=felis&felis=eu&donec=sapien&semper=cursus&sapien=vestibulum&a=proin&libero=eu&nam=mi&dui=nulla&proin=ac&leo=enim&odio=in&porttitor=tempor&id=turpis&consequat=nec", "date": "7/7/2022" },
  { "id": 6, "ip_address": "225.220.93.110", "name": "Fix San", "url": "https://kickstarter.com/ultrices/vel/augue/vestibulum/ante/ipsum.jsp?posuere=ac&felis=consequat&sed=metus&lacus=sapien&morbi=ut&sem=nunc&mauris=vestibulum&laoreet=ante&ut=ipsum&rhoncus=primis&aliquet=in&pulvinar=faucibus&sed=orci&nisl=luctus&nunc=et&rhoncus=ultrices&dui=posuere&vel=cubilia&sem=curae&sed=mauris&sagittis=viverra&nam=diam&congue=vitae&risus=quam&semper=suspendisse&porta=potenti&volutpat=nullam&quam=porttitor&pede=lacus&lobortis=at&ligula=turpis&sit=donec&amet=posuere&eleifend=metus&pede=vitae&libero=ipsum&quis=aliquam&orci=non&nullam=mauris&molestie=morbi&nibh=non&in=lectus&lectus=aliquam&pellentesque=sit&at=amet&nulla=diam&suspendisse=in&potenti=magna&cras=bibendum&in=imperdiet&purus=nullam&eu=orci&magna=pede&vulputate=venenatis&luctus=non&cum=sodales&sociis=sed&natoque=tincidunt&penatibus=eu&et=felis&magnis=fusce&dis=posuere&parturient=felis&montes=sed&nascetur=lacus&ridiculus=morbi&mus=sem&vivamus=mauris&vestibulum=laoreet&sagittis=ut&sapien=rhoncus&cum=aliquet&sociis=pulvinar&natoque=sed&penatibus=nisl&et=nunc&magnis=rhoncus&dis=dui&parturient=vel&montes=sem&nascetur=sed&ridiculus=sagittis&mus=nam&etiam=congue&vel=risus&augue=semper&vestibulum=porta&rutrum=volutpat", "date": "12/14/2022" },
  { "id": 7, "ip_address": "216.117.122.186", "name": "Otcom", "url": "http://woothemes.com/ac/leo.json?vitae=nulla&ipsum=neque&aliquam=libero&non=convallis&mauris=eget&morbi=eleifend&non=luctus&lectus=ultricies&aliquam=eu&sit=nibh&amet=quisque&diam=id&in=justo&magna=sit&bibendum=amet&imperdiet=sapien&nullam=dignissim&orci=vestibulum&pede=vestibulum&venenatis=ante&non=ipsum&sodales=primis&sed=in", "date": "8/9/2022" },
  { "id": 8, "ip_address": "147.71.111.176", "name": "Tresom", "url": "https://huffingtonpost.com/vivamus/vestibulum/sagittis/sapien/cum/sociis.js?ipsum=dis&primis=parturient&in=montes&faucibus=nascetur&orci=ridiculus&luctus=mus&et=vivamus&ultrices=vestibulum&posuere=sagittis&cubilia=sapien&curae=cum&donec=sociis&pharetra=natoque&magna=penatibus&vestibulum=et&aliquet=magnis&ultrices=dis&erat=parturient&tortor=montes&sollicitudin=nascetur&mi=ridiculus&sit=mus&amet=etiam&lobortis=vel&sapien=augue&sapien=vestibulum&non=rutrum&mi=rutrum&integer=neque&ac=aenean&neque=auctor&duis=gravida&bibendum=sem&morbi=praesent&non=id&quam=massa&nec=id&dui=nisl&luctus=venenatis&rutrum=lacinia&nulla=aenean&tellus=sit&in=amet&sagittis=justo&dui=morbi&vel=ut&nisl=odio&duis=cras&ac=mi&nibh=pede&fusce=malesuada&lacus=in&purus=imperdiet&aliquet=et&at=commodo&feugiat=vulputate&non=justo&pretium=in&quis=blandit&lectus=ultrices&suspendisse=enim", "date": "2/18/2023" },
  { "id": 9, "ip_address": "189.202.82.86", "name": "Opela", "url": "https://nasa.gov/cursus/vestibulum/proin/eu.jpg?lacus=in&morbi=hac&quis=habitasse&tortor=platea&id=dictumst&nulla=morbi&ultrices=vestibulum", "date": "8/6/2022" },
  { "id": 10, "ip_address": "21.26.2.160", "name": "Namfix", "url": "https://princeton.edu/molestie/lorem/quisque/ut/erat/curabitur.aspx?magna=ut&bibendum=blandit&imperdiet=non&nullam=interdum&orci=in&pede=ante&venenatis=vestibulum&non=ante&sodales=ipsum&sed=primis&tincidunt=in&eu=faucibus&felis=orci&fusce=luctus&posuere=et&felis=ultrices&sed=posuere&lacus=cubilia&morbi=curae&sem=duis&mauris=faucibus&laoreet=accumsan&ut=odio&rhoncus=curabitur&aliquet=convallis&pulvinar=duis&sed=consequat&nisl=dui&nunc=nec&rhoncus=nisi&dui=volutpat&vel=eleifend&sem=donec&sed=ut&sagittis=dolor&nam=morbi&congue=vel", "date": "2/7/2023" },
  { "id": 11, "ip_address": "121.43.225.243", "name": "Viva", "url": "http://cyberchimps.com/tristique/in/tempus.xml?luctus=ut&rutrum=rhoncus&nulla=aliquet&tellus=pulvinar&in=sed&sagittis=nisl&dui=nunc&vel=rhoncus", "date": "12/14/2022" },
  { "id": 12, "ip_address": "113.250.175.203", "name": "Flowdesk", "url": "https://vkontakte.ru/sollicitudin/mi/sit/amet/lobortis/sapien.aspx?hac=posuere&habitasse=nonummy&platea=integer&dictumst=non&maecenas=velit&ut=donec&massa=diam&quis=neque&augue=vestibulum&luctus=eget&tincidunt=vulputate&nulla=ut&mollis=ultrices&molestie=vel&lorem=augue&quisque=vestibulum&ut=ante", "date": "10/23/2022" },
  { "id": 13, "ip_address": "117.22.151.68", "name": "Opela", "url": "http://ucla.edu/turpis/elementum/ligula/vehicula/consequat/morbi/a.png?interdum=morbi&mauris=non&non=lectus&ligula=aliquam&pellentesque=sit&ultrices=amet&phasellus=diam&id=in&sapien=magna&in=bibendum&sapien=imperdiet&iaculis=nullam&congue=orci&vivamus=pede&metus=venenatis&arcu=non&adipiscing=sodales&molestie=sed&hendrerit=tincidunt&at=eu", "date": "4/21/2022" },
  { "id": 14, "ip_address": "245.10.10.33", "name": "Flowdesk", "url": "https://ovh.net/magnis/dis/parturient/montes/nascetur.aspx?dapibus=eros&dolor=vestibulum&vel=ac&est=est&donec=lacinia&odio=nisi&justo=venenatis&sollicitudin=tristique&ut=fusce&suscipit=congue&a=diam&feugiat=id&et=ornare&eros=imperdiet&vestibulum=sapien&ac=urna&est=pretium&lacinia=nisl&nisi=ut&venenatis=volutpat&tristique=sapien&fusce=arcu&congue=sed&diam=augue&id=aliquam&ornare=erat&imperdiet=volutpat&sapien=in&urna=congue&pretium=etiam&nisl=justo&ut=etiam&volutpat=pretium&sapien=iaculis&arcu=justo&sed=in&augue=hac&aliquam=habitasse&erat=platea&volutpat=dictumst&in=etiam&congue=faucibus&etiam=cursus&justo=urna&etiam=ut&pretium=tellus&iaculis=nulla&justo=ut&in=erat", "date": "8/2/2022" },
  { "id": 15, "ip_address": "1.169.108.118", "name": "Redhold", "url": "https://dailymotion.com/morbi/porttitor.png?nulla=massa&nisl=id&nunc=nisl&nisl=venenatis&duis=lacinia&bibendum=aenean&felis=sit&sed=amet&interdum=justo&venenatis=morbi&turpis=ut&enim=odio&blandit=cras&mi=mi&in=pede&porttitor=malesuada&pede=in&justo=imperdiet&eu=et&massa=commodo&donec=vulputate&dapibus=justo&duis=in&at=blandit&velit=ultrices&eu=enim&est=lorem&congue=ipsum&elementum=dolor&in=sit&hac=amet&habitasse=consectetuer&platea=adipiscing&dictumst=elit&morbi=proin&vestibulum=interdum&velit=mauris&id=non&pretium=ligula&iaculis=pellentesque&diam=ultrices&erat=phasellus&fermentum=id&justo=sapien&nec=in&condimentum=sapien&neque=iaculis&sapien=congue&placerat=vivamus&ante=metus&nulla=arcu&justo=adipiscing&aliquam=molestie&quis=hendrerit&turpis=at&eget=vulputate&elit=vitae", "date": "12/27/2022" },
  { "id": 16, "ip_address": "88.214.212.98", "name": "Zaam-Dox", "url": "http://buzzfeed.com/porta/volutpat/erat/quisque/erat/eros/viverra.png?id=pharetra&turpis=magna&integer=ac&aliquet=consequat&massa=metus&id=sapien&lobortis=ut&convallis=nunc&tortor=vestibulum&risus=ante&dapibus=ipsum&augue=primis&vel=in", "date": "7/26/2022" },
  { "id": 17, "ip_address": "76.156.43.33", "name": "Gembucket", "url": "https://chron.com/at/nibh/in/hac.js?natoque=rutrum&penatibus=neque&et=aenean&magnis=auctor&dis=gravida&parturient=sem&montes=praesent&nascetur=id&ridiculus=massa&mus=id&vivamus=nisl&vestibulum=venenatis&sagittis=lacinia&sapien=aenean&cum=sit&sociis=amet&natoque=justo&penatibus=morbi&et=ut&magnis=odio&dis=cras&parturient=mi&montes=pede&nascetur=malesuada&ridiculus=in&mus=imperdiet&etiam=et&vel=commodo&augue=vulputate&vestibulum=justo&rutrum=in&rutrum=blandit&neque=ultrices&aenean=enim&auctor=lorem&gravida=ipsum&sem=dolor&praesent=sit&id=amet&massa=consectetuer&id=adipiscing&nisl=elit&venenatis=proin&lacinia=interdum&aenean=mauris&sit=non&amet=ligula&justo=pellentesque&morbi=ultrices&ut=phasellus&odio=id&cras=sapien&mi=in&pede=sapien&malesuada=iaculis&in=congue&imperdiet=vivamus&et=metus&commodo=arcu&vulputate=adipiscing&justo=molestie&in=hendrerit&blandit=at&ultrices=vulputate&enim=vitae&lorem=nisl&ipsum=aenean&dolor=lectus&sit=pellentesque&amet=eget&consectetuer=nunc&adipiscing=donec&elit=quis&proin=orci&interdum=eget&mauris=orci&non=vehicula&ligula=condimentum&pellentesque=curabitur&ultrices=in&phasellus=libero", "date": "5/24/2022" },
  { "id": 18, "ip_address": "153.222.43.170", "name": "Quo Lux", "url": "https://geocities.jp/suspendisse/potenti/in.xml?nulla=turpis&ultrices=donec&aliquet=posuere&maecenas=metus&leo=vitae&odio=ipsum&condimentum=aliquam&id=non&luctus=mauris&nec=morbi&molestie=non&sed=lectus&justo=aliquam&pellentesque=sit&viverra=amet&pede=diam&ac=in&diam=magna&cras=bibendum&pellentesque=imperdiet&volutpat=nullam&dui=orci&maecenas=pede&tristique=venenatis&est=non&et=sodales&tempus=sed&semper=tincidunt&est=eu&quam=felis&pharetra=fusce&magna=posuere&ac=felis&consequat=sed&metus=lacus&sapien=morbi&ut=sem&nunc=mauris&vestibulum=laoreet&ante=ut&ipsum=rhoncus&primis=aliquet&in=pulvinar&faucibus=sed&orci=nisl&luctus=nunc&et=rhoncus&ultrices=dui&posuere=vel&cubilia=sem&curae=sed&mauris=sagittis&viverra=nam&diam=congue&vitae=risus&quam=semper&suspendisse=porta&potenti=volutpat&nullam=quam&porttitor=pede&lacus=lobortis&at=ligula&turpis=sit&donec=amet&posuere=eleifend&metus=pede&vitae=libero&ipsum=quis&aliquam=orci&non=nullam&mauris=molestie&morbi=nibh&non=in&lectus=lectus&aliquam=pellentesque&sit=at&amet=nulla&diam=suspendisse&in=potenti&magna=cras&bibendum=in&imperdiet=purus&nullam=eu&orci=magna&pede=vulputate&venenatis=luctus&non=cum", "date": "7/27/2022" },
  { "id": 19, "ip_address": "233.177.245.157", "name": "Domainer", "url": "http://dedecms.com/amet/diam/in/magna/bibendum/imperdiet.jpg?eu=pede&orci=justo&mauris=lacinia&lacinia=eget&sapien=tincidunt&quis=eget&libero=tempus&nullam=vel&sit=pede&amet=morbi&turpis=porttitor&elementum=lorem&ligula=id&vehicula=ligula", "date": "4/11/2023" },
  { "id": 20, "ip_address": "215.159.150.108", "name": "Y-Solowarm", "url": "https://wufoo.com/pede/ullamcorper/augue/a/suscipit.jsp?eget=eget&nunc=orci&donec=vehicula&quis=condimentum&orci=curabitur&eget=in&orci=libero&vehicula=ut&condimentum=massa&curabitur=volutpat&in=convallis&libero=morbi&ut=odio&massa=odio&volutpat=elementum&convallis=eu&morbi=interdum&odio=eu&odio=tincidunt&elementum=in&eu=leo&interdum=maecenas&eu=pulvinar&tincidunt=lobortis&in=est&leo=phasellus&maecenas=sit&pulvinar=amet&lobortis=erat&est=nulla&phasellus=tempus&sit=vivamus&amet=in&erat=felis&nulla=eu&tempus=sapien&vivamus=cursus&in=vestibulum&felis=proin&eu=eu&sapien=mi&cursus=nulla&vestibulum=ac&proin=enim&eu=in&mi=tempor&nulla=turpis&ac=nec&enim=euismod&in=scelerisque&tempor=quam&turpis=turpis&nec=adipiscing&euismod=lorem&scelerisque=vitae&quam=mattis&turpis=nibh&adipiscing=ligula&lorem=nec&vitae=sem&mattis=duis&nibh=aliquam&ligula=convallis&nec=nunc&sem=proin&duis=at", "date": "5/7/2022" },
  { "id": 21, "ip_address": "1.176.151.186", "name": "Solarbreeze", "url": "https://narod.ru/pellentesque.json?vulputate=eu&luctus=felis&cum=fusce&sociis=posuere&natoque=felis&penatibus=sed&et=lacus&magnis=morbi&dis=sem&parturient=mauris&montes=laoreet&nascetur=ut&ridiculus=rhoncus&mus=aliquet&vivamus=pulvinar&vestibulum=sed&sagittis=nisl&sapien=nunc&cum=rhoncus&sociis=dui&natoque=vel&penatibus=sem&et=sed&magnis=sagittis&dis=nam&parturient=congue&montes=risus&nascetur=semper&ridiculus=porta&mus=volutpat&etiam=quam&vel=pede&augue=lobortis&vestibulum=ligula&rutrum=sit&rutrum=amet&neque=eleifend&aenean=pede&auctor=libero&gravida=quis&sem=orci&praesent=nullam&id=molestie&massa=nibh&id=in&nisl=lectus&venenatis=pellentesque&lacinia=at&aenean=nulla&sit=suspendisse&amet=potenti&justo=cras&morbi=in&ut=purus&odio=eu&cras=magna&mi=vulputate&pede=luctus&malesuada=cum&in=sociis&imperdiet=natoque&et=penatibus&commodo=et&vulputate=magnis&justo=dis&in=parturient&blandit=montes&ultrices=nascetur&enim=ridiculus&lorem=mus&ipsum=vivamus&dolor=vestibulum&sit=sagittis&amet=sapien&consectetuer=cum&adipiscing=sociis&elit=natoque&proin=penatibus&interdum=et&mauris=magnis&non=dis&ligula=parturient&pellentesque=montes&ultrices=nascetur&phasellus=ridiculus&id=mus&sapien=etiam&in=vel&sapien=augue", "date": "7/23/2022" },
  { "id": 22, "ip_address": "146.63.36.108", "name": "Fixflex", "url": "http://bravesites.com/aenean/sit/amet/justo.aspx?in=semper&lectus=rutrum&pellentesque=nulla&at=nunc&nulla=purus&suspendisse=phasellus&potenti=in&cras=felis&in=donec&purus=semper&eu=sapien&magna=a&vulputate=libero&luctus=nam&cum=dui&sociis=proin&natoque=leo&penatibus=odio", "date": "4/17/2023" },
  { "id": 23, "ip_address": "232.209.191.142", "name": "Subin", "url": "https://nytimes.com/mauris/sit/amet.jpg?ipsum=eget&primis=nunc&in=donec&faucibus=quis&orci=orci", "date": "8/5/2022" },
  { "id": 24, "ip_address": "201.226.117.93", "name": "Bytecard", "url": "https://nytimes.com/nec/dui/luctus/rutrum/nulla/tellus/in.html?at=donec&turpis=odio&donec=justo&posuere=sollicitudin&metus=ut&vitae=suscipit&ipsum=a&aliquam=feugiat&non=et&mauris=eros&morbi=vestibulum&non=ac&lectus=est&aliquam=lacinia&sit=nisi&amet=venenatis&diam=tristique", "date": "3/17/2023" }
]
</script>

<style scoped>
#searchResults {
  margin-top: 1.25rem;
  margin-bottom: 1.25rem;
  border-radius: 0.375rem;
  border-width: 1px;
  border-color: rgb(229 231 235);
  padding: 1rem 1.5rem 1rem 1.5rem;
}

.dark #searchResults {
  border-color: var(--slate);
}

ul#searchResults li {
  padding: 1rem 0;
}

</style>